public class HelloWorld {                              // [1]
    public static void main(String[] args) {         // [2]
        System.out.println("Hello world"); // [3]
System.out.println("Agnieszka"); //[4]
    System.out.println("46"); //[5]
    System.out.println("LK");}}  //[6]